### ISSUE TITLE
[Issue]: Bazel building failed with webpack rules

### ISSUE THREAD

**Issue by fy2462** [aspect-build/rules_webpack#101]
### What happened?
I am working on building FE with bazel.
It can building well with `./node_modules/.bin/webpack --progress --mode=production --stats=minimal `. But failed with bazel.

```14:31:55) ERROR: /autra/modules/dreamview/frontend/BUILD:45:15: Running Webpack [Webpack] failed: (Exit 1): webpack.sh failed: error executing command bazel-out/k8-opt-exec-2B5CBBC6/bin/modules/dreamview/frontend/webpack.sh -c modules/dreamview/frontend/bundle_dist.webpack.config.js -c modules/dreamview/frontend/webpack.config.js --merge ... (remaining 5 arguments skipped)
(node:148110) [DEP_WEBPACK_COMPILATION_ADDITIONAL_CHUNK_ASSETS] DeprecationWarning: additionalChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(Use `node --trace-deprecation ...` to show where the warning was created)
4 assets
2 modules

ERROR in ./app.tsx
Module build failed (from ../../../../node_modules/.aspect_rules_js/babel-loader@8.3.0_idmflsbzmivcz6fnnmcaipezqe/node_modules/babel-loader/lib/index.js):
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@babel/plugin-proposal-decorators' imported from /autra/.cache/bazel/cb92cb09597ef463226f6e13f5e110cf/execroot/autra/bazel-out/k8-opt/bin/babel-virtual-resolve-base.js
    at new NodeError (/autra/.cache/bazel/cb92cb09597ef463226f6e13f5e110cf/execroot/autra/bazel-out/k8-opt/bin/node_modules/.aspect_rules_js/@babel+core@7.21.0/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:2240:5)
    at packageResolve (/autra/.cache/bazel/cb92cb09597ef463226f6e13f5e110cf/execroot/autra/bazel-out/k8-opt/bin/node_modules/.aspect_rules_js/@babel+core@7.21.0/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:2776:9)
    at moduleResolve (/autra/.cache/bazel/cb92cb09597ef463226f6e13f5e110cf/execroot/autra/bazel-out/k8-opt/bin/node_modules/.aspect_rules_js/@babel+core@7.21.0/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:2804:18)
    at defaultResolve (/autra/.cache/bazel/cb92cb09597ef463226f6e13f5e110cf/execroot/autra/bazel-out/k8-opt/bin/node_modules/.aspect_rules_js/@babel+core@7.21.0/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:2835:13)
    at /autra/.cache/bazel/cb92cb09597ef463226f6e13f5e110cf/execroot/autra/bazel-out/k8-opt/bin/node_modules/.aspect_rules_js/@babel+core@7.21.0/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:2855:14
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/autra/.cache/bazel/cb92cb09597ef463226f6e13f5e110cf/execroot/autra/bazel-out/k8-opt/bin/node_modules/.aspect_rules_js/@babel+core@7.21.0/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:45:103)
    at _next (/autra/.cache/bazel/cb92cb09597ef463226f6e13f5e110cf/execroot/autra/bazel-out/k8-opt/bin/node_modules/.aspect_rules_js/@babel+core@7.21.0/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:46:194)
    at /autra/.cache/bazel/cb92cb09597ef463226f6e13f5e110cf/execroot/autra/bazel-out/k8-opt/bin/node_modules/.aspect_rules_js/@babel+core@7.21.0/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:46:364
    at new Promise (<anonymous>)
    at /autra/.cache/bazel/cb92cb09597ef463226f6e13f5e110cf/execroot/autra/bazel-out/k8-opt/bin/node_modules/.aspect_rules_js/@babel+core@7.21.0/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:46:97
    at _resolve (/autra/.cache/bazel/cb92cb09597ef463226f6e13f5e110cf/execroot/autra/bazel-out/k8-opt/bin/node_modules/.aspect_rules_js/@babel+core@7.21.0/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:2862:19)
    at resolve (/autra/.cache/bazel/cb92cb09597ef463226f6e13f5e110cf/execroot/autra/bazel-out/k8-opt/bin/node_modules/.aspect_rules_js/@babel+core@7.21.0/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:2847:19)
    at /autra/.cache/bazel/cb92cb09597ef463226f6e13f5e110cf/execroot/autra/bazel-out/k8-opt/bin/node_modules/.aspect_rules_js/@babel+core@7.21.0/node_modules/@babel/core/lib/config/files/import-meta-resolve.js:27:38
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/autra/.cache/bazel/cb92cb09597ef463226f6e13f5e110cf/execroot/autra/bazel-out/k8-opt/bin/node_modules/.aspect_rules_js/@babel+core@7.21.0/node_modules/@babel/core/lib/config/files/import-meta-resolve.js:15:103)

ERROR in bundle_dist
Module not found: Error: Can't resolve './modules/dreamview/frontend/src/app.tsx' in '/autra/.cache/bazel/cb92cb09597ef463226f6e13f5e110cf/execroot/autra/bazel-out/k8-opt/bin/modules/dreamview/frontend/src'

ERROR in TypeError: Cannot read properties of undefined (reading 'tap')
  
  - ExternalModuleFactoryPlugin.js:17 ExternalModuleFactoryPlugin.apply
    [bin]/[webpack@4.46.0_webpack-cli@4.10.0]/[webpack]/lib/ExternalModuleFactor    yPlugin.js:17:37
  
  - ExternalsPlugin.js:16 
    [bin]/[webpack@4.46.0_webpack-cli@4.10.0]/[webpack]/lib/ExternalsPlugin.js:1    6:63
  
  
  - Hook.js:14 Hook.CALL_DELEGATE [as _call]
    [bin]/[tapable@2.2.1]/[tapable]/lib/Hook.js:14:14
  
  - Compiler.js:1164 
    [bin]/[webpack@5.75.0_webpack-cli@5.0.1]/[webpack]/lib/Compiler.js:1164:23
  
  
  - Hook.js:18 Hook.CALL_ASYNC_DELEGATE [as _callAsync]
    [bin]/[tapable@2.2.1]/[tapable]/lib/Hook.js:18:14
  
  - Compiler.js:1161 Compiler.compile
    [bin]/[webpack@5.75.0_webpack-cli@5.0.1]/[webpack]/lib/Compiler.js:1161:28
  
  - Compiler.js:561 Compiler.runAsChild
    [bin]/[webpack@5.75.0_webpack-cli@5.0.1]/[webpack]/lib/Compiler.js:561:8
  
  - compiler.js:129 
    [bin]/[html-webpack-plugin@4.0.0_webpack@4.46.0]/[html-webpack-plugin]/lib/c    ompiler.js:129:21
  
  - new Promise
  
  - compiler.js:128 HtmlWebpackChildCompiler.compileTemplates
    [bin]/[html-webpack-plugin@4.0.0_webpack@4.46.0]/[html-webpack-plugin]/lib/c    ompiler.js:128:31
  
  - compiler.js:260 Object.compileTemplate
    [bin]/[html-webpack-plugin@4.0.0_webpack@4.46.0]/[html-webpack-plugin]/lib/c    ompiler.js:260:24
  
  - index.js:153 
    [bin]/[html-webpack-plugin@4.0.0_webpack@4.46.0]/[html-webpack-plugin]/index    .js:153:42
  
  
  - Hook.js:18 Hook.CALL_ASYNC_DELEGATE [as _callAsync]
    [bin]/[tapable@2.2.1]/[tapable]/lib/Hook.js:18:14

webpack 5.75.0 compiled with 3 errors in 1142 ms
```

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`:

bazel 5.1.1

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

rules_webpack-0.9.1

Language(s) and/or frameworks involved:

JavaScript

### How to reproduce

```shell
bazel build //modules/dreamview/frontend:bundle_dist
```

### Any other information?

the BUILD file

```BUILD
load("@aspect_rules_webpack//webpack:defs.bzl", "webpack_binary", "webpack_bundle")
load("@npm//:defs.bzl", "npm_link_all_packages")
load("@aspect_rules_js//js:defs.bzl", "js_library")
load("//buildtools/install:install.bzl", "install_files")

package(default_visibility = ["//visibility:public"])

npm_link_all_packages(name = "node_modules")

filegroup(
    name = "frontend_src",
    srcs = glob([
        "src/**/*",
        "proto_bundle/*.json",
        "assets/**/*",
    ]),
)

filegroup(
    name = "frontend_config",
    srcs = [
        ".babelrc",
        ".eslintrc",
        ".prettierignore",
        ".prettierrc.js",
        "global.d.ts",
        "tsconfig.json",
        "webpack.config.js",
    ],
)

js_library(
    name = "webpack_config",
    deps = [
        ":node_modules/webpack",
    ],
)

webpack_binary(
    name = "webpack",
    node_modules = ":node_modules",
)

webpack_bundle(
    name = "bundle_dist",
    srcs = [
        ":frontend_src",
        ":frontend_config",
    ],
    entry_point = "src/app.tsx",
    args = [
        "--progress",
        "--mode=production",
        "--stats=minimal",
    ],
    webpack = ":webpack",
    webpack_config = "webpack.config.js",
    output_dir = True,
    deps = [
        ":webpack_config",
    ],
)
```

Webpack.js

```
'use strict';

const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const WebpackBar = require('webpackbar');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const ESLintPlugin = require('eslint-webpack-plugin');
const TSLintPlugin = require('tslint-webpack-plugin');
const PermissionsOutputPlugin = require('webpack-permissions-plugin');

module.exports = (env, argv) => {
  const mode = argv.mode || 'development';
  const isDev = mode === 'development';
  const proto_base_directory = (env && env.bazel_out_directory) || __dirname;
  const proto_bundle_path = path.resolve(proto_base_directory, 'proto_bundle');
  const autra_base_directory =
    (env && env.bazel_out_directory) || 'modules/dreamview/frontend/';
  const autra_modules_path = path.resolve(autra_base_directory, 'autra_modules_wasm');
  return {
    mode,
    entry: {
      app: './app.tsx',
      parameters: path.join(__dirname, 'src/store/config/parameters.yml')
    },
    context: path.join(__dirname, 'src'),

    output: {
      path: path.join(__dirname, 'dist'),
      filename: '[name].[chunkhash].bundle.js',
      chunkFilename: '[name].[chunkhash].chunk.js',
      publicPath: '/'
    },

    // Enable it when needed in local dev
    devtool: 'inline-source-map',

    resolve: {
      // Files with the following extensions here can be "import"
      // without the extension.
      //
      // Needs ".json" and ".scss" for Grommet.
      extensions: [
        '.webpack.js',
        '.web.js',
        '.jsx',
        '.js',
        '.ts',
        '.tsx',
        '.json',
        '.scss',
        '.css',
        '.less',
        '.png',
        '.svg',
        '.wasm'
      ],
      alias: {
        store: path.resolve(__dirname, 'src/store'),
        styles: path.resolve(__dirname, 'src/styles'),
        components: path.resolve(__dirname, 'src/components'),
        utils: path.resolve(__dirname, 'src/utils'),
        renderer: path.resolve(__dirname, 'src/renderer'),
        v2: path.resolve(__dirname, 'src/v2'),
        assets: path.resolve(__dirname, 'assets'),
        proto_bundle: path.resolve(proto_bundle_path),
      }
    },

    module: {
      rules: [
        {
          test: /\.[tj]sx?$/,
          exclude: /node_modules/,
          use: [
            {
              loader: 'babel-loader',
              options: {
                presets: [
                  ['@babel/preset-env', { targets: 'defaults' }],
                  '@babel/preset-react',
                  '@babel/preset-typescript'
                ],
                plugins: [
                  ['@babel/plugin-proposal-decorators', { legacy: true }],
                  ['@babel/plugin-proposal-class-properties', { loose: false }],
                  '@babel/plugin-transform-runtime',
                  '@babel/plugin-proposal-object-rest-spread',
                  '@babel/plugin-syntax-export-default-from',
                  '@babel/plugin-proposal-optional-chaining'
                ]
              }
            }
          ]
        },
        {
          test: /\.yml$/,
          exclude: /node_modules/,
          use: [{ loader: 'json-loader' }, { loader: 'yaml-loader' }]
        },
        {
          // Object models and materials.
          test: /\.mtl$|\.obj$/,
          exclude: /node_modules/,
          use: [
            {
              loader: 'file-loader'
            }
          ]
        },
        {
          // Load the images. They goes through image-webpack-loader
          // first, and then file-loader.
          //
          // Now you can import images just like js.
          test: /\.(png|jpe?g|svg|mp4|mov|gif|mp3)$/i,
          use: [
            {
              loader: 'file-loader',
              options: {
                name: 'assets/[hash:base64:55].[ext]'
              }
            },
            {
              loader: 'image-webpack-loader',
              options: {
                pngquant: {
                  quality: [0.65, 0.9],
                  speed: 4
                },
                mozjpeg: {
                  progressive: true
                }
              }
            }
          ]
        },
        {
          // This is to apply the following style loaders in (reverse) order.
          // Grommet scss files needs to be processed this way.
          test: /\.(sa|sc|c)ss$/,
          use: [
            {
              loader: 'style-loader'
            },
            {
              loader: 'css-loader'
            },
            {
              loader: 'fast-sass-loader',
              options: {
                includePaths: ['./node_modules']
              }
            }
          ]
        },
        {
          test: /\.less$/,
          use: [
            {
              loader: 'style-loader'
            },
            {
              loader: 'css-loader'
            },
            {
              loader: 'less-loader',
              options: {
                lessOptions: {
                  javascriptEnabled: true
                }
              }
            }
          ]
        },
        {
          // For font-awesome (woff)
          test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
          use: [
            {
              loader: 'url-loader',
              options: {
                limit: 10000,
                mimetype: 'application/font-woff'
              }
            }
          ]
        },
        {
          // For font-awesome (ttf)
          test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
          loader: 'file-loader'
        },
        {
          test: /\.js$/,
          include: [path.resolve(__dirname, 'src/utils/webworker')],
          use: [
            {
              loader: 'babel-loader',
              options: {
                cacheDirectory: true,
                presets: [['@babel/preset-env', { targets: 'defaults' }]]
              }
            }
          ]
        },
        {
          test: /parameters.yml/,
          use: [
            {
              loader: 'file-loader',
              options: {
                name: '[name].json',
                context: 'src/store/config',
                outputPath: '.' // the "dist" dir
              }
            },
            {
              loader: 'yaml-loader'
            }
          ]
        },
        {
          test: /autra_modules\.wasm$/,
          type: 'javascript/auto',
          use: [
            {
              loader: 'file-loader',
              options: {
                name: '[name].[hash].wasm'
              }
            }
          ]
        }
      ]
    },

    plugins: [
      // Generate the actual html from the hbs.
      new HtmlWebpackPlugin({
        favicon: './favicon.png',
        template: './index.hbs',
        // Include only the app. Do not include the service worker.
        chunks: ['app']
      }),
      new CopyWebpackPlugin([
        {
          from: '../node_modules/three/examples/fonts',
          to: 'fonts'
        }
      ]),

      new webpack.DefinePlugin({
        OFFLINE_PLAYBACK: JSON.stringify(false)
      }),

      new ESLintPlugin({
        cache: true,
        extensions: ['js', 'jsx', 'ts', 'tsx']
      }),

      argv.mode === 'development' ? new TSLintPlugin() : null
    ].filter(Boolean),

    devServer: {
      // hide webpack warning overlay in dev
      client: {
        overlay: false
      },
      server: {
        type: 'http'
      },
      host: '0.0.0.0',
      port: 8080,
      // open: ['http://localhost:8080'],
      static: {
        directory: path.join(__dirname, 'src'),
        serveIndex: true,
        watch: true
      },
      // Ask react-router instead of the server to handle routes.
      historyApiFallback: true,
      allowedHosts: 'all',
      proxy: {
        context: () => true,
        target: 'http://localhost:8888'
      },
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Headers': '*',
        'Access-Control-Allow-Methods': '*',
        'Cross-Origin-Embedder-Policy': 'require-corp',
        'Cross-Origin-Opener-Policy': 'same-origin'
      }
    },
    watchOptions: {
      ignored: /node_modules/
    },

    // Disable the warning of large size bundle files.
    performance: {
      hints: false
    }
  };
};

```

### Fund our work

- [x] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by fy2462** [comment]
Hi, @gregmagolan, This problem has troubled me for a long time, all works well when using `/node_modules/.bin/webpack serve --progress`, but failed with bazel, any idea? thansk.

**Comment by fy2462** [comment]
![image](https://user-images.githubusercontent.com/7626394/220659258-446942ee-ab3c-4e7c-9a8c-c137d03bab6e.png)
Great work, thanks.

**Comment by gregmagolan** [comment]
Thanks you for your support on Open Collective 💚 

Webpack under Bazel can be a little tricky. We've had to spend up to a few days working through pathing issues with some plugins and custom webpack configs at clients. I know that webpack can be sensitive to the CWD when it runs so to start I would try setting `chdir = package_name()` so the current working directory when you webpack is run under Bazel is the directory of the Bazel package the target is in.

https://github.com/aspect-build/rules_webpack/blob/main/docs/rules.md#webpack_bundle-chdir

**Comment by fy2462** [comment]
@gregmagolan Thanks your nice reply. I fixed this issue with chdir field. but the same issue happened next with this [link](https://github.com/aspect-build/rules_js/issues/903).

I install all package in my modules package.json. But the bazel still do not find the dependency. I have to repeated install them in root package.json. and then bazel can find them.

is it a bug? why rule_js can not find them in my node_modules?
How to change my config to fix that, thanks.

**Comment by fy2462** [comment]
> Thanks you for your support on Open Collective green_heart
> 
> Webpack under Bazel can be a tricky in some configurations. We've had to spend up to a few days working through pathing issues with some plugins and custom webpack configs at clients while doing Bazel migrations. I know that webpack can be sensitive to the CWD when it runs so to start I would try setting `chdir = package_name()` so the current working directory when you webpack is run under Bazel is the directory of the Bazel package the target is in.
> 
> https://github.com/aspect-build/rules_webpack/blob/main/docs/rules.md#webpack_bundle-chdir

Thanks your help, I have fixed the issue by adding `'@luma.gl/core': path.resolve(__dirname, 'node_modules/@luma.gl/core')` to resolve.alias in webpack_config. Thank you again.
