### ISSUE TITLE
Issue: Webpack can't find it's plugin depedencies like "mini-css-extract-plugin"

### ISSUE THREAD

**Issue by carlblock** [aspect-build/rules_webpack#57]
Hi there,

I'm using PNPM with workspaces and running the webpack build outside the context of bazel it works. However with the rules_webpack webpack seem unable to find one of it's plugin dependencies for css. In this case "mini-css-extract-plugin".

I've tried to experiment a bit with removing "mini-css-extract-plugin" from the "srcs" but in that case I get a typical NPM "MODULE_NOT_FOUND" error from NPM. However with it added to the srcs array, webpack complains about ENOENT instead. The deps array with it added or not does not seem to affect the ENOENT error. 

In the project's node_modules folder I have the mini-css-extract-plugin folder symlinked by pnpm install operation.

I'm not sure if this is some issue with my configuration or with webpack in the bazel context.

Thanks in advance!

Below is the error output and configuration files:

`ls -lah`in the private folder of bazel context
```shell
(px_platform) {10:54}~/git/px_platform:carl/frontend-pnpm ✗ ➭ ls -lah /private/var/tmp/_bazel_carl/15c8a2d882d962809a84e8e4728b9912/sandbox/darwin-sandbox/303/execroot/px_platform/bazel-out/darwin_arm64-fastbuild/bin/projects/frontend/components-library/node_modules/mini-css-extract-plugin/dist/
total 144
dr-xr-xr-x  8 carl  wheel   256B Oct 18 10:32 .
dr-xr-xr-x  8 carl  wheel   256B Oct 18 10:32 ..
dr-xr-xr-x  4 carl  wheel   128B Oct 18 10:32 hmr
-r-xr-xr-x  1 carl  wheel    40K Oct 18 10:32 index.js
-r-xr-xr-x  1 carl  wheel   1.0K Oct 18 10:32 loader-options.json
-r-xr-xr-x  1 carl  wheel    12K Oct 18 10:32 loader.js
-r-xr-xr-x  1 carl  wheel   2.6K Oct 18 10:32 plugin-options.json
-r-xr-xr-x  1 carl  wheel   5.2K Oct 18 10:32 utils.js
```

### Bazel webpack call:
```
ERROR: /Users/carl/git/px_platform/projects/frontend/components-library/BUILD.bazel:20:15: Running Webpack [Webpack] failed: (Exit 2): sandbox-exec failed: error executing command 
  (cd /private/var/tmp/_bazel_carl/15c8a2d882d962809a84e8e4728b9912/sandbox/darwin-sandbox/298/execroot/px_platform && \
  exec env - \
    BAZEL_BINDIR=bazel-out/darwin_arm64-fastbuild/bin \
    TMPDIR=/var/folders/ml/_tqr6h590cg8j56w5lqd9ymc0000gn/T/ \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_carl/15c8a2d882d962809a84e8e4728b9912/sandbox/darwin-sandbox/298/sandbox.sb /var/tmp/_bazel_carl/install/0876258cc54d1db936e99308dafd6883/process-wrapper '--timeout=0' '--kill_delay=15' bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/webpack/webpack.sh -c projects/frontend/components-library/components_library.webpack.config.js -c projects/frontend/components-library/webpack.config.js --merge --devtool eval --mode development --output-path projects/frontend/components-library/components_library)
[webpack-cli] Failed to load '/private/var/tmp/_bazel_carl/15c8a2d882d962809a84e8e4728b9912/sandbox/darwin-sandbox/298/execroot/px_platform/bazel-out/darwin_arm64-fastbuild/bin/projects/frontend/components-library/webpack.config.js' config
```

### Error output:
```
[webpack-cli] Error: ENOENT: no such file or directory, realpath '/private/var/tmp/_bazel_carl/15c8a2d882d962809a84e8e4728b9912/sandbox/darwin-sandbox/298/execroot/px_platform/bazel-out/darwin_arm64-fastbuild/bin/projects/frontend/components-library/node_modules/mini-css-extract-plugin/dist/index.js'
    at enoent (/private/var/tmp/_bazel_carl/15c8a2d882d962809a84e8e4728b9912/external/aspect_rules_js/js/private/node-patches/fs.js:803:15)
    at guardedRealPathSync (/private/var/tmp/_bazel_carl/15c8a2d882d962809a84e8e4728b9912/external/aspect_rules_js/js/private/node-patches/fs.js:701:27)
    at Object.fs.realpathSync (/private/var/tmp/_bazel_carl/15c8a2d882d962809a84e8e4728b9912/external/aspect_rules_js/js/private/node-patches/fs.js:181:20)
    at toRealPath (node:internal/modules/cjs/loader:394:13)
    at tryFile (node:internal/modules/cjs/loader:390:10)
    at tryPackage (node:internal/modules/cjs/loader:346:16)
    at Function.Module._findPath (node:internal/modules/cjs/loader:566:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  errno: -2,
  syscall: 'realpath',
  code: 'ENOENT',
  path: '/private/var/tmp/_bazel_carl/15c8a2d882d962809a84e8e4728b9912/sandbox/darwin-sandbox/298/execroot/px_platform/bazel-out/darwin_arm64-fastbuild/bin/projects/frontend/components-library/node_modules/mini-css-extract-plugin/dist/index.js'
}

```

### webpack.config.js
```js
const path = require('path')
const MiniCssExtractPlugin = require("mini-css-extract-plugin");

const SRC_PATH = 'src/lib'
module.exports = (env) => {
    return {
      mode: process.env.NODE_ENV ? 'production': '',
      entry: {
        index: path.resolve(SRC_PATH, 'index.ts'),
        fonts: path.resolve(SRC_PATH, 'fonts.ts'),
      },
      optimization: {
        minimize: process.env.WEBPACK_WATCH,
      },
      output: {
        filename: '[name].js',
        path: path.resolve(__dirname, 'dist'),
        library: {
          type: 'commonjs2', // Same as what react and react-dom uses
        }
      },
      externals: {
        // Don't bundle react or react-dom
        react: {
          commonjs2: "react",
        },
        'react-dom': {
          commonjs2: "react-dom",
        }
      },
      plugins: [
        new MiniCssExtractPlugin(),
      ],
      module: {
        rules: [
          {
            test: /\.(js|jsx)$/i,
            exclude: /(node_modules)/,
            use: {
              loader: 'babel-loader',
              options: {
                presets: ['@babel/preset-env'],
              },
            }
          },
          {
            test: /\.(tsx)?$/,
            use: [
              {
                loader: 'ts-loader',
              }
            ],
            exclude: /node_modules/,
          },
          {
            test: /\.css$/i,
            use: [
              {
                loader: MiniCssExtractPlugin.loader,
                options: {
                  esModule: true,
                },
              },
              'css-loader',
              'postcss-loader'
            ],
          },
          // Images
          {
            test: /\.(png|jpg|jpeg|gif)$/i,
            type: 'asset/resource',
          },
          // Svg from style assets
          {
            test: /\.(svg)$/i,
            type: 'asset/resource',
            issuer: /\.s?css$/,
          },
          // Svg from components
          {
            test: /\.(svg)$/i,
            enforce: 'pre',
            loader: require.resolve('@svgr/webpack'),
            issuer: /\.(js|jsx|tsx)$/i,
          },
          // font assets
          {
            test: /\.(woff|woff2|eot|ttf|otf)$/i,
            type: 'asset/resource',
          },
        ],
      },
      resolve: {
        extensions: ['.js', '.jsx', '.ts', '.tsx'],
        symlinks: true,
        // alias: {
        //   'react': path.resolve(__dirname, './node_modules/react'),
        //   'react-dom': path.resolve(__dirname, './node_modules/react-dom'),
        // }
      },
    }
}
```
### BUILD.bazel
```bazel
load("@npm//:defs.bzl", "npm_link_all_packages")

npm_link_all_packages(name = "node_modules")

load("@aspect_rules_webpack//webpack:defs.bzl", "webpack_bundle")

webpack_bundle(
    name = "components_library",
    srcs = [":node_modules/mini-css-extract-plugin"],
    #    args = [
    #        "--mode",
    #        "production",
    #    ],
    data = [
        ":package.json",
    ],
    entry_points = {
        "//projects/frontend/components-library/src/lib:index.ts": "index",
        "//projects/frontend/components-library/src/lib:fonts.ts": "fonts",
    },
    output_dir = True,
    supports_workers = False,
    webpack_config = ":webpack.config.js",
    # deps = [":node_modules/mini-css-extract-plugin"],
)

```

**Comment by sureyeaah** [comment]
Have you tried replacing `srcs` with `deps`?

**Comment by cgrindel** [comment]
@carlblock Were you able to try @sureyeaah suggestion?

**Comment by gregmagolan** [comment]
@sureyeaah If you could put up a minimal repro I can take a look at what is going on. Hard to say from just code snippets.

**Comment by carlblock** [comment]
Hey, sorry for the late answer but I had to take some days out! I haven't narrowed down yet exactly. However after trial & error, and looking around of other github issues especially of webpack it also seems like webpack itself has a lot of issues with the way that pnpm symlinks the packages.

@gregmagolan, I'll get around today to create a minimal repo to replicate the issue.

@sureyeaah yes, this is already something I have tried but the issue remains.

Also an interesting thing I found, inside the project folder in the bazel-out i find an empty generated folder(`components_library`) with the name of the bazel rule.
<img width="406" alt="Screenshot 2022-11-03 at 11 49 47" src="https://user-images.githubusercontent.com/5603121/199702199-e415306e-6da4-472d-b8a7-e7125e57930a.png">

**Comment by stoiky** [comment]
`:node_modules/mini-css-extract-plugin` should be in `deps`. 

For me it works, but the transitive dependency of it is not linked in the package store to be found at runtime.
In this case it won't find `schema-utils` just like for https://github.com/aspect-build/rules_js/issues/611

Similar issues can happen while trying to use loaders like `source-map-loader` and `ts-loader`. I'll create a repro and share here soon.
